# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
array = np.array([23,101,45,86,11])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
array.sort()
print(array)

[ 11  23  45  86 101]


# Problem 2

In [23]:
import numpy as np
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
Series = np.array([10,15,30,45,60])
print(Series)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
Series1 = np.arange(5,15)
print(Series1)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
Series2 = np.arange(50,100,5)
print(Series2)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
Series3 = np.zeros(10)
print(Series3)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
Series5 = np.ones(10)
print(Series5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
Series6 = np.linspace(0,100,5)
print(Series6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
Series7 = np.random.randint(10,30,5)
print(Series7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
Series8 = np.random.uniform(-1,1,10)
print(Series8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
Matris = np.random.randint(10,50, size=(3,5))

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satirToplam = np.sum(Matris, axis=1)
sutunToplam = np.sum(Matris, axis=0) 
print("Satır Toplamı: ", satirToplam)  
print("Sütun Toplamı: ", sutunToplam )

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
matrisMax = np.max(Matris) 
matrisMin = np.min(Matris)
print("En büyük değer: ", matrisMax)  
print("En küçük değer: ", matrisMin )

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(np.argmax(Matris))

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
Series9 = np.random.randint(10,20, size=7)
print(Series9[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(Series9[::-1]) 

# 15- Üretilen matrisin ilk satırını seçiniz.
print(Matris[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(Matris[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(Matris[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(Matris**2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
Matris = np.random.randint(-50, 50, size=(3,5))
print((Matris > 0) & (Matris % 2 == 0))

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[18 11 10 22 16]
[ 0.18801007  0.81582162  0.41275809 -0.86689653 -0.26108561 -0.02648033
 -0.11184041 -0.84070613 -0.62776238 -0.34621575]
Satır Toplamı:  [130 152 177]
Sütun Toplamı:  [ 59 118  86  90 106]
En büyük değer:  49
En küçük değer:  11
12
[10 11 19]
[17 13 17 13 19 11 10]
[11 45 21 29 24]
16
[11 12 36]
[[ 121 2025  441  841  576]
 [ 144 1089  256 1849 2304]
 [1296 1600 2401  324 1156]]
[[False False  True  True  True]
 [ True False False False False]
 [ True False False False False]]
