# Problem 1

In [15]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a = np.array([1,2,3,4,5,6,7,8,9,10])
multi = a.reshape(2,5)
print(multi)

# 3 - matris'in boyutunu öğrenin
print(multi.shape)

# 4 - matris'i yeniden boyutlandırın
newMatrix = multi.reshape(5,2)
print(newMatrix)
# 5 - matris'in boyut sayısını öğrenin
print(multi.ndim)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2


# Problem 2

In [38]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
birdenOna = [0,1,2,3,4,5,6,7,8,9,10]
liste = []
for i in range(0,10):
    if i%2 == 1:
        liste.append(i)
array = np.array(liste)
print(array)

# 2 - Oluşturduğunuz matrisi parçalayın
secondMatrix = np.array(5,1)
print(secondMatrix)

# 3 - Parçalanmış matrisleri birleştirin
artıkMatrix = birdenOna - secondMatrix
print(artıkMatrix)


[1 3 5 7 9]


TypeError: Cannot interpret '1' as a data type

# Problem 3

In [41]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
a = np.arange(5, 100, 2)
print(a)
# 2 - matris'in özelliklerini inceleyin


[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51
 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99]
